services:
  lotr-app:
    container_name: lotr-app-prod
    build:
      context: ../..
      dockerfile: Dockerfile
      target: prod
    image: lotr-api:prod
    restart: always
    ports:
      - "${APP_PORT}:9525"
    env_file:
      - .env
    depends_on:
      lotr-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9525/api/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - net-backend

  lotr-db:
    container_name: lotr-db-prod
    image: mysql/mysql-server:8.0
    restart: always
    ports:
      - "${DB_PORT_EXPOSED}:${DB_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - lotr-db-prod-vol:/var/lib/mysql
      - ../../sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
    networks:
      - net-backend

networks:
  net-backend:
    driver: bridge

volumes:
  lotr-db-prod-vol:
